In [1]:
import pandas as pd
import re
import matplotlib.pyplot as plt
import math
import numpy as np
import random
import pandas as pd
from sklearn.cluster import KMeans
import re
from Route import *
from Solution import * 
from sklearn.cluster import KMeans
from vrp_problem import *

In [2]:
customers_array,DEPOT = load_data()

#customers_df = cluster_df(customers_df,20)
n_generation = 300
n_population = 100 
co_rate = 0.8
m_rate = 0.3
n_clusters = 20
pop = generate_initial_population(customers_array, n_population,n_clusters,DEPOT)
pop_fitness = [sol.fitness_func() for sol in pop]

best_idx = pop_fitness.index(max(pop_fitness))
best_sol_ever = pop[best_idx]

for g in range(n_generation):
    print(f"Genration:{g}")
    pop = generate_initial_population(customers_array, n_population,n_clusters,DEPOT)
    print("Population created")
    parent1,parent2 = rank_based_selection(pop,2)
    print("Two parents created")
    offspring = create_offspring(parent1,parent2,co_rate)
    print("an offspring created")
    # Mutate offspring
    for route in offspring.routes:
        route.mutate(m_rate)
    print(f"Route mutated")


    # Calculate fitness for offspring
    offspring_fitness = offspring.fitness_func()
    print(f"offspring fitness:{offspring_fitness}")
    print("offspring solution:")
    print(len(offspring.routes),offspring.total_distance,offspring.get_total_customers_served(),offspring.check_feasibility(),offspring.fitness_func())
    print("-"*50)

    if offspring.get_total_customers_served()>100:
        break

    # Replace worst solution in population with offspring
    pop_fitness = [sol.fitness_func() for sol in pop]

    worst_idx = pop_fitness.index(min(pop_fitness))
    print(f"worest solution fitness:{pop_fitness[worst_idx]}")


    if offspring_fitness > pop_fitness[worst_idx]:
        pop[worst_idx] = offspring


    best_idx = pop_fitness.index(max(pop_fitness))
    best_sol = pop[best_idx]

    if best_sol.fitness_func() > best_sol_ever.fitness_func():
        best_sol_ever = best_sol
    print("best solution till now:")
    print(len(best_sol_ever.routes),best_sol_ever.get_total_solution_distance(),best_sol_ever.get_total_customers_served(),best_sol_ever.check_feasibility(),best_sol_ever.fitness_func())
    print("-"*50)


Genration:0
Population created
Two parents created
an offspring created
Route mutated
offspring fitness:0.0
offspring solution:
20 2101.95794908132 106 0 0.0
--------------------------------------------------


In [6]:
for route in offspring.routes:
    print(route.customers_ids)

[15. 45. 17. 39. 87. 44.]
[28. 29. 70. 53. 13. 77. 41. 54.]
[69. 78. 71. 81.]
[72. 35. 67. 36.]
[32. 83. 63. 31. 89. 83.  9.]
[100.  19.  86.  88.   7.  95. 100.]
[40. 24. 68.]
[98. 38. 97. 98.]
[65. 50.]
[73.  3. 16. 22. 76. 74. 23. 42. 58.]
[60. 93. 43. 46.  6. 96. 84. 46. 62.]
[57. 56. 55. 75.  5. 25. 26.]
[ 2. 51. 27.  2.]
[ 92. 101.  94.]
[14. 90. 59.]
[47. 18. 49.]
[34. 30. 52. 80. 30. 79. 10.]
[91. 11. 21. 33.]
[32. 63. 31. 89.  8.]
[100.  41.  19.  88.  54.   7.  95.]


In [7]:
offspring.prevent_duplicated_customers()

customers array is empty?!


IndexError: index 0 is out of bounds for axis 0 with size 0