In [1]:
import pandas as pd
import re
import matplotlib.pyplot as plt
import math
import numpy as np
import random
import pandas as pd
from sklearn.cluster import KMeans
import re
from Route import *
from Solution import * 
from sklearn.cluster import KMeans
from vrp_problem import *

In [2]:
customers_array,DEPOT = load_data()

#customers_df = cluster_df(customers_df,20)
n_generation = 300
n_population = 100 
co_rate = 0.8
m_rate = 0.3
n_clusters = 20
pop = generate_initial_population(customers_array, n_population,n_clusters,DEPOT)
pop_fitness = [sol.fitness_func() for sol in pop]

best_idx = pop_fitness.index(max(pop_fitness))
best_sol_ever = pop[best_idx]

for g in range(n_generation):
    print(f"Genration:{g}")
    pop = generate_initial_population(customers_array, n_population,n_clusters,DEPOT)
    print("Population created")
    parent1,parent2 = rank_based_selection(pop,2)
    print("Two parents created")
    offspring = create_offspring(parent1,parent2,co_rate)
    print("an offspring created")
    # Mutate offspring
    for route in offspring.routes:
        route.mutate(m_rate)
    print(f"Route mutated")


    # Calculate fitness for offspring
    offspring_fitness = offspring.fitness_func()
    print(f"offspring fitness:{offspring_fitness}")
    print("offspring solution:")
    print(len(offspring.routes),offspring.total_distance,offspring.get_total_customers_served(),offspring.check_feasibility(),offspring.fitness_func())
    print("-"*50)

    if offspring.get_total_customers_served()>100:
        break

    # Replace worst solution in population with offspring
    pop_fitness = [sol.fitness_func() for sol in pop]

    worst_idx = pop_fitness.index(min(pop_fitness))
    print(f"worest solution fitness:{pop_fitness[worst_idx]}")


    if offspring_fitness > pop_fitness[worst_idx]:
        pop[worst_idx] = offspring


    best_idx = pop_fitness.index(max(pop_fitness))
    best_sol = pop[best_idx]

    if best_sol.fitness_func() > best_sol_ever.fitness_func():
        best_sol_ever = best_sol
    print("best solution till now:")
    print(len(best_sol_ever.routes),best_sol_ever.get_total_solution_distance(),best_sol_ever.get_total_customers_served(),best_sol_ever.check_feasibility(),best_sol_ever.fitness_func())
    print("-"*50)


Genration:0
Population created
Two parents created
an offspring created
Route mutated
offspring fitness:0.0
offspring solution:
20 2105.9662232157393 100 0 0.0
--------------------------------------------------
worest solution fitness:0.0
best solution till now:
20 2067.4469715224855 100 0 0.0
--------------------------------------------------
Genration:1
Population created
Two parents created
an offspring created
Route mutated
offspring fitness:0.0
offspring solution:
20 2051.733652089914 100 0 0.0
--------------------------------------------------
worest solution fitness:0.0
best solution till now:
20 2067.4469715224855 100 0 0.0
--------------------------------------------------
Genration:2
Population created
Two parents created
an offspring created
Route mutated
offspring fitness:0.0
offspring solution:
20 1991.9565708617297 102 0 0.0
--------------------------------------------------


In [3]:
for route in offspring.routes:
    print(route.customers_ids)

[ 98.  38.  97.  92.  61. 101.  94.]
[34. 70. 13. 77.]
[43. 15. 16.]
[30. 52. 80. 82. 79. 10.  4. 35.]
[28. 29. 41. 54. 27.]
[ 98.  38.  97.  92.  61. 101.  94.]
[57. 56. 55. 75.  5. 25. 26.]
[99. 17. 62. 86. 85.]
[14. 90. 14.]
[40. 24. 68.]
[46. 84. 32. 83. 63. 89.  8.  9.]
[45. 39. 87. 44.]
[47. 18. 49.]
[60.  6.  6. 96.  3.]
[66. 72. 67. 36.]
[ 53. 100.  19.  88.   7.  95.]
[51. 69.  2. 78. 71. 81.]
[31. 91. 11. 21. 31.]
[73. 22. 76. 74. 23. 42. 58.]
[65. 50.]


In [4]:
offspring.prevent_duplicated_customers()

customers:[ 98.  38.  97.  92.  61. 101.  94.]
customers:[34. 70. 13. 77.]
customers:[43. 15. 16.]
customers:[30. 52. 80. 82. 79. 10.  4. 35.]
customers:[28. 29. 41. 54. 27.]
customers:[ 98.  38.  97.  92.  61. 101.  94.]
customer:98.0 duplicated!
customer:38.0 duplicated!
customer:97.0 duplicated!
customer:92.0 duplicated!
customer:61.0 duplicated!
customer:101.0 duplicated!
customer:94.0 duplicated!
customers:[57. 56. 55. 75.  5. 25. 26.]
customers:[99. 17. 62. 86. 85.]
customers:[14. 90. 14.]
customer:14.0 duplicated!
customers:[40. 24. 68.]
customers:[46. 84. 32. 83. 63. 89.  8.  9.]
customers:[45. 39. 87. 44.]
customers:[47. 18. 49.]
customers:[60.  6.  6. 96.  3.]
customer:6.0 duplicated!
customers:[66. 72. 67. 36.]
customers:[ 53. 100.  19.  88.   7.  95.]
customers:[51. 69.  2. 78. 71. 81.]
customers:[31. 91. 11. 21. 31.]
customer:31.0 duplicated!
customers:[73. 22. 76. 74. 23. 42. 58.]
customers:[65. 50.]
customer:98.0, row:98.0
customer:38.0, row:38.0
customer:97.0, row:97.0


In [5]:
print(len(offspring.routes),offspring.get_total_solution_distance(),offspring.get_total_customers_served(),offspring.check_feasibility(),offspring.fitness_func())


19 1876.7317325608883 92 0 0.0
